version: 0.0
os: linux
files:
  - source: /
    destination: /opt/mcs
hooks:
  ApplicationStop:
    - location:
  AfterInstall:
    - location: /install_packages.sh
      timeout: 300
      runas: root