version: 0.0
os: linux
files:
  - source: /
    destination: /opt/mcs
hooks:
  ApplicationStop:
    - location: /actions/stop_service
      timeout: 3500
      runas: root
  AfterInstall:
    - location: /actions/install_packages
      timeout: 300
      runas: root
  ApplicationStart:
    - location: /actions/start_service
      timeout: 300
      runas: root
file_exists_behavior: OVERWRITE